version: '3'
services:
  # Django web server
  web:
    image: web:local
    build:
      context: ./django
      dockerfile: Dockerfile
    hostname: web
    command: python -m gunicorn casestudy.asgi:application -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level debug
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=casestudy.settings
    env_file:
      - django/.env

  # Postgres
  db:
    image: postgres:15-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
      image: redis:7-alpine3.18
      hostname: redis
      ports: 
        - "6379:6379"

  # React app
  app:
    image: app:local
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/
      - /app/node_modules
    ports:
      - "3000:3000"

  # Celery worker
  celery:
    image: web:local
    command: celery -A casestudy worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=casestudy.settings
    env_file:
      - django/.env
  
  # Celery beat
  celery-beat:
    image: web:local
    command: celery -A casestudy beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=casestudy.settings
    env_file:
      - django/.env

volumes:
    postgres_data:
