# Generated by Django 4.2 on 2023-08-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ticker', models.TextField()),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
        ),
    ]
