# Generated by Django 4.2 on 2023-09-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='security',
            name='ticker',
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
